services:
  kafkaintegration.api:
    image: ${DOCKER_REGISTRY-}kafkaintegrationapi
    build:
      context: .
      dockerfile: src/KafkaIntegration.Api/Dockerfile
    networks:
      - kafka-net
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      # KRaft rejimi uchun kerakli sozlamalar
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      
      # Tinglovchilar (Listeners) sozlamalari
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      
      # Cluster ID - KRaft uchun majburiy (ixtiyoriy UUID)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # Boshqa sozlamalar
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  kafka-net:
    driver: bridge